apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-model
spec:
  name: iris
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: localhost:5000/custom-model:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
    graph:
      name: classifier
    name: default
    replicas: 1